version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST_DEV=host.docker.internal # For connecting to XAMPP on the host
      - DB_USER_DEV=root
      - DB_PASSWORD_DEV=
      - DB_NAME_DEV=test
      - DB_HOST_PROD=mysql
      - DB_USER_PROD=user
      - DB_PASSWORD_PROD=password
      - DB_NAME_PROD=proddb
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proddb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mysql-data:
